<script>
    export default{
       
    };
</script>



<template>
    <div class="row align-items-md-center" id="banner">
      <div class="col-6 banner-introduct">
        <span class="banner-title">
          Chào mừng bạn đến Nature Comestic
        </span>
        <p class="banner-des">
          Hãy duy trì làn da khoẻ mạnh với sản phẩm mới nhất của chúng tôi, ở đây sản phẩm được sản xuất từ 100% thiên nhiên , không chất bảo quản, hoá chất, yên tâm mà sử dụng.
        </p>
        <a href="" class="banner-button btn-box dark"> XEM NGAY</a>
      </div>
      <div class="col-6 banner-image">
        <img src="https://theme.hstatic.net/200000244895/1000651353/14/img_intro_product_1.png?v=2319" alt="">
      </div>
    </div>

    <div class="row align-items-md-center" id="hotproduct">
      <div class="col-6 banner-image">
        <img src="https://theme.hstatic.net/200000244895/1000651353/14/img_intro_product_2.png?v=2319" alt="">
      </div>
      <div class="col-6 hotproduct-introduct">
        <span class="banner-title">
          Sản phẩm nổi bật
        </span>
        <p class="banner-des">
          Với các sản phẩm của chúng tôi, chúng tôi luôn uy tín đặc lên hàng đầu , bảo đảm sức khoẻ cho khách hàng yên tâm sử dụng.
        </p>
        <a href="" class="banner-button btn-box dark"> XEM NGAY</a>
      </div>
    </div>
</template>


