<script>
    export default{
       
    };
</script>

<template>
    <div class="row align-items-md-center p-0" id="banner">
      <div class="col-5 banner-introduct p-5">
        <h3 class="banner-title">
          Chào mừng bạn đến Nature Comestic
        </h3>
        <p class="banner-des">
          Hãy duy trì làn da khoẻ mạnh với sản phẩm mới nhất của chúng tôi, ở đây sản phẩm được sản xuất từ 100% thiên nhiên , không chất bảo quản, hoá chất, yên tâm mà sử dụng.
        </p>
        <a href="/product" class="banner-button btn-box dark"> XEM NGAY</a>
      </div>
      <div class="col-6 banner-image p-0">
        <img src="https://cosmeticsbusiness.com/article-image-alias/embrace-the-new-with-hpc-packaging-2.jpeg" alt="">
      </div>
    </div>

    <div class="row align-items-md-center" id="hotproduct">
      <div class="col-6 banner-image p-0">
        <img src="https://dtd31o1ybbmk8.cloudfront.net/photos/ed5c0e62b43d7c4a1445231f9c8c0962/thumb.jpg" alt="">
      </div>
      <div class="col-5 hotproduct-introduct p-5">
        <span class="banner-title">
          Sản phẩm nổi bật
        </span>
        <p class="banner-des">
          Với các sản phẩm của chúng tôi, chúng tôi luôn uy tín đặc lên hàng đầu , bảo đảm sức khoẻ cho khách hàng yên tâm sử dụng.
        </p>
        <a href="/product" class="banner-button btn-box dark"> XEM NGAY</a>
      </div>
    </div>
</template>


