<script>
    export default{
       
    };
</script>


<template>
    <footer class="row card-footer footer text-start m-0">
     <div class="col-6">
         <h3>THÔNG TIN LIÊN HỆ</h3>
         <p>Địa chỉ: Đường 3/2, phường Xuân Khánh, Quận Ninh Kiều, thành phố Cần Thơ</p>
         <p>Holine: 0909 89 12 62</p>
         <p>
             Liên hệ với chúng tôi:
             <a href="https://m.facebook.com/"><img src="https://o.remove.bg/downloads/1bc3a880-a028-46fd-81aa-eb7ed5638f54/cute-social-media-logo-Facebook-png-removebg-preview.png" alt=""></a>
             <a href="https://www.instagram.com/"><img src="https://o.remove.bg/downloads/8540919f-45da-4e1a-8dfd-aa7a52a09c68/-51608580992f2v8cpwdxq-removebg-preview.png" alt=""></a>
             <a href="https://twitter.com/"><img src="https://o.remove.bg/downloads/f1b04bfe-1354-42a1-8590-89a9792f0a48/cute-social-media-logo-Twitter-png-removebg-preview.png" alt=""></a>
         </p>
     </div>
       <div class="col-6 text-center mt-4 p-0 footer-right">
        <h2 id="title">Nature Comestic</h2>
        <p>Chào mừng bạn đến với Nature Comestic. Tại đây, bạn sẽ tìm thấy hoàn toàn mọi thứ bạn cần để thể hiện công việc kinh doanh theo định hướng chăm sóc sức khỏe, spa hoặc sắc đẹp của mình theo cách hiện đại.</p>
     </div>
 </footer>
</template>
